routes/web.php
<?php
Route::group(['middleware' => 'auth'], function(){
	Route::get('/', 'HomeController@index');

	Route::group(['prefix' => 'secretary', 'namespace' => 'Secretary', 'middleware' => 'profile:Secretaria'], function(){
		Route::get('/', 'HomeController@index');
	});
	Route::group(['prefix' => 'traumatologo', 'namespace' => 'Traumatologist', 'middleware' => 'profile:Traumatólogo'], function(){
		Route::get('/', 'HomeController@index');

		Route::get('create/{id}', 'RecordController@createRecord');
		Route::post('printorder/{record}', 'RecordController@printOrder');
		Route::get('records/{record}/print', 'RecordController@print');
		Route::post('print-massive', 'RecordController@printMassive');
		Route::post('saveorder', 'RecordController@saveOrder');
		Route::resource('records', 'RecordController');
	});
	Route::group(['prefix' => 'kinesiologo', 'namespace' => 'Kinesiologist', 'middleware' => 'profile:Kinesiólogo'], function(){
		Route::get('/', 'HomeController@index');

		Route::get('create/{id}', 'RecordController@createRecord');
		Route::get('records/{record}/print', 'RecordController@print');
		Route::resource('records', 'RecordController');
	});


	Route::group(['prefix' => 'api', 'namespace' => 'Api'], function(){

		Route::get('session', 'SessionController@index');

		Route::get('branches/{id}/last-hours', 'BranchController@lastFreeHours');

		Route::resource('branches', 'BranchController');
		Route::resource('branches.paymentboxes', 'BranchPaymentBoxController');
		Route::resource('branches.doctors', 'BranchDoctorController');
		Route::resource('patients', 'PatientController');
		Route::resource('insurancecompanies', 'InsuranceCompanyController');
		Route::resource('comercialcompanies', 'ComercialCompanyController');
		Route::resource('attentiontypes', 'AttentionTypeController');
		Route::resource('payments', 'PaymentController');
		Route::resource('records', 'RecordController');

		Route::get('doctors/dailyhours', 'DoctorController@dailyHours');
		Route::get('doctors/dailyhoursbetween', 'DoctorController@dailyHoursBetween');
		Route::get('doctors/dailyhoursbetweenkine', 'DoctorController@dailyHoursBetweenKine');
		Route::get('doctors/resumehours', 'DoctorController@resumeHours');
		Route::get('doctors/resumehoursbetween', 'DoctorController@resumeHoursBetween');
		Route::get('doctors/allbookingfordate', 'DoctorController@allBookingForDate');

		Route::post('bookings/search', 'BookingController@search');
		Route::post('bookings/lock', 'BookingController@lock');
		Route::post('bookings/unlock', 'BookingController@unlock');
		Route::post('bookings/cancel', 'BookingController@cancel');
		Route::post('bookings/{booking}/patient-actitude', 'BookingController@setPatientActitude');
		Route::post('bookings/{booking}/receipt', 'BookingController@receipt');
		Route::resource('patients', 'PatientController');
		Route::resource('products', 'ProductController');

		Route::group(['prefix' => 'secretary', 'namespace' => 'Secretary', 'middleware' => 'profile:Secretaria'], function(){

			Route::group(['prefix' => 'session'], function(){

				Route::any('ask-for-open-box', 'SessionController@askForOpenBox');
				Route::any('open-box', 'SessionController@openBox');
				Route::any('close-box', 'SessionController@closeBox');

			});

		});
	});

	Route::group(['prefix' => 'administrador', 'namespace' => 'Admin'], function(){
		Route::get('/', 'HomeController@index');
		Route::resource('users', 'UserController');
		Route::resource('branches', 'BranchController');
		Route::resource('attentiontypes', 'AttentionTypeController');
		Route::resource('paymentboxes', 'PaymentBoxController');
		Route::resource('commercialcompanies', 'CommercialCompanyController');
		Route::resource('healthcompanies', 'HealthCompanyController');
		Route::resource('insurancecompanies', 'InsuranceCompanyController');
		Route::resource('products', 'ProductController');
		Route::resource('patients', 'PatientController');
		Route::resource('hourly', 'HourlyController');
	});

	Route::group(['prefix' => 'administrativo', 'namespace' => 'Administrative'], function(){
		Route::get('/', 'HomeController@index');
		Route::resource('sales-resume', 'SalesResumeController');
		Route::resource('sales-detailed', 'SalesDetailedController');
	});

	Route::get('download/{id}/{filename}', ['uses' => 'FileController@download', 'as' => 'files.download']);
	Route::get('showfile/{id}/{filename}', ['uses' => 'FileController@show', 'as' => 'files.show']);
});

Route::group(['prefix' => 'api', 'namespace' => 'Api'], function(){
	Route::get('doctors/freehours', 'DoctorController@freeHours');
	Route::get('doctors/{doctor}/freehours/{branch}/{date}', 'DoctorController@oldFreeHours');
	Route::resource('doctors', 'DoctorController');
	Route::resource('bookings', 'BookingController');
	Route::resource('healthcompanies', 'HealthCompanyController');
});

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout');

app/Models/Patient.php
<?php
namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Patient extends Model
{
    use SoftDeletes;
    use Notifiable;
    protected $dates = ['created_at', 'updated_at', 'deleted_at', 'birthdate'];

    function getFullnameAttribute(){
        return $this->firstname . ' ' . $this->lastname;
    }
    function getFullnameInverseAttribute(){
        return $this->lastname . ' ' . $this->firstname;
    }

    function bookings(){
        return $this->hasMany('App\Models\Patient\Booking')->orderBy('bookingdate');
    }
}

app/Http/Controllers/Traumatologist/HomeController.php
<?php

namespace App\Http\Controllers\Traumatologist;

use App\Http\Controllers\Controller;
use App\Models\Doctor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class HomeController extends Controller
{
    function index(Request $request){
    	$currentDoctor = Doctor::find(auth()->user()->id);

    	return view('traumatologist.index', compact('currentDoctor'));
    }
}

app/Http/Controllers/Traumatologist/RecordController.php
<?php

namespace App\Http\Controllers\Traumatologist;

use App\Http\Controllers\Controller;
use App\Models\Doctor;
use App\Models\Param\Branch;
use App\Models\Patient;
use App\Models\Patient\Booking;
use App\Models\Patient\Record;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class RecordController extends Controller
{

    function index(Request $request){
        $records = Record::whereId(0);
        $ok = false;

        if(count($request->input()) > 0):
            $records = Record::with('patient', 'doctor', 'branch')->orderBy('attentiondate', 'desc');

            if($request->has('record') and is_numeric($request->input('record'))):
                $records = $records->whereId($request->input('record'));
                $ok = true;
            endif;

            if($request->has('date')):
                $records = $records->whereDate('attentiondate', $request->input('date'));
                $ok = true;
            endif;

            if($request->has('patient_rut') and $request->input('patient_rut') != ''):
                $patient = Patient::whereRut($request->input('patient_rut'))->first();
                $id = ($patient) ? $patient->id : null;

                $records = $records->wherePatientId($id);
                $ok = true;
            endif;

            if($request->has('patient_name') and $request->input('patient_name') != ''):

                $patientsId = Patient::where('firstname', 'like', '%' . $request->input('patient_name') . '%')->orWhere('lastname', 'like', '%' . $request->input('patient_name') . '%')->get()->pluck('id')->toArray();
                if(count($patientsId) > 0):
                    $records = $records->whereIn('patient_id', $patientsId);
                    $ok = true;
                else:
                    $ok = false;
                endif;
            endif;
        endif;

        if(!$ok)
            $records = Record::whereId(0);

        $records = $records->paginate();

        $selectedDate = $request->input('date');
        $selectedPatientRut = $request->input('patient_rut');
        $selectedPatientName = $request->input('patient_name');
        $selectedRecord = $request->input('record');

        return view('traumatologist.records',
            compact('records', 'selectedDate', 'selectedPatientRut', 'selectedPatientName', 'selectedRecord')
        );
    }

    function createRecord(Request $request, $id){
    	$booking = Booking::find($id);
    	if(!$booking)
    		return back()
    			->with('error', true)
    			->with('message', 'La reserva no existe!');

    	$record = Record::whereBookingId($id)->first();
    	if(!$record):
    		$record = new Record;
    		$record->booking_id = $booking->id;
    		$record->patient_id = $booking->patient_id;
    		$record->branch_id = $booking->branch_id;
    		$record->doctor_id = $booking->doctor_id;
    		$record->attentiondate = new Carbon;
    		$record->save();
    	endif;

    	return redirect()->action('Traumatologist\RecordController@edit', $record->id);
    }

    function edit(Request $request, $id){
    	$record = Record::find($id);
    	if(!$record)
    		return back()
    			->with('type', 'danger')
    			->with('message', 'La ficha no existe!');

    	$currentDoctor = Doctor::find(auth()->user()->id);

        $now = new Carbon();
        $isOwner = (auth()->user()->id == $record->doctor_id);
        $allowEditing = ($isOwner === true and $record->attentiondate->diffInHours($now) <= 48);

    	return view('traumatologist.edit',
            compact('record', 'currentDoctor', 'allowEditing', 'isOwner')
        );
    }

    function update(Request $request, $id){
    	$record = Record::find($id);
    	if(!$record)
    		return back()
    			->with('type', 'danger')
    			->with('message', 'La ficha no existe!');

    	$record->anamnesis = $request->input('anamnesis');
    	$record->physical_exam = $request->input('physical_exam');
    	$record->diagnosis = $request->input('diagnosis');
    	$record->save();

    	$patient = $record->patient;
    	$patient->family_history = $request->input('family_history');
    	$patient->save();

    	return back()
    		->with('type', 'success')
    		->with('message', 'La ficha fue guardada correctamente.');
    }

    function printOrder(Request $request, $record_id){
        $record = Record::find($record_id);
        if(!$record)
            return "La ficha médica no existe!";

    	$orderDetails = $request->input('orderDetails');
    	$doctorInfo = [
    		'doctor_fullname' 	=> $request->input('doctor_fullname'),
    		'doctor_speciality' => $request->input('doctor_speciality'),
    		'doctor_rut' 		=> $request->input('doctor_rut'),
    		'doctor_rcm' 		=> $request->input('doctor_rcm')
    	];

    	$html = view('traumatologist.printorder', compact('orderDetails', 'doctorInfo'))->render();
        $filename = 'order_' . $record_id . '_' . date('YmdHis') . '.html';

        Storage::put('uploads/' . $filename, $html);

        $record->files()->create([
            'author_id' => auth()->id(),
            'filename' => $filename,
            'realname' => $filename,
            'size' => 0,
            'mime' => 'text/html'
        ]);

        return $html;
    }

    function print(Request $request, $record_id){
        $record = Record::find($record_id);
        if(!$record)
            return "La ficha médica no existe!";

        return view('traumatologist.print',
            compact('record')
        );
    }

    function printMassive(Request $request){
        $ids = $request->input('print_ids', []);
        if(!is_array($ids) or count($ids) == 0)
            return "No ha seleccionado ninguna ficha a imprimir.";

        $records = Record::whereIn('id', $ids)->get();
        return view('traumatologist.printmassive',
            compact('records')
        );
    }
}

resources/views/traumatologist/edit.blade.php
@extends('traumatologist.layout')
@section('s-content')

@if($allowEditing)
{{ Form::open(['action' => ['Traumatologist\RecordController@update', $record->id], 'method' => 'PUT']) }}
@endif

<h1>Ficha Médica Nº {{ $record->id }}</h1>

<div class="main-box">
	<header class="main-box-header clearfix">
		<a href="{{ action('Traumatologist\HomeController@index') }}" class="btn btn-default btn-xs">
			<i class="fa fa-chevron-circle-left"></i> Volver
		</a>
		<a href="{{ action('Traumatologist\RecordController@index', ['patient_rut' => $record->patient->rut]) }}" class="btn btn-default">
			<i class="fa fa-history"></i> Historial Médico del Paciente
		</a>
		<a href="{{ action('Traumatologist\RecordController@print', $record->id) }}" target="_blank" class="btn btn-default">
			<i class="fa fa-print"></i> Imprimir
		</a>
		<div class="pull-right">
			@if($allowEditing)
			<button type="button" @click="openMedicalOrderDialog()" class="btn btn-default"><i class="fa fa-plus-circle"></i> Nueva orden médica</button>
			<button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o"></i> Guardar cambios</button>
			@endif
		</div>
	</header>
</div>

@if($isOwner and !$allowEditing)
<div class="alert alert-warning">
	<i class="fa fa-archive"></i> Esta ficha ha sido archivada ya que han pasado más de 48 horas desde
	la atención médica.
</div>
@endif

<div class="main-box">
	<header class="main-box-header clearfix">
		<h2>Datos del Paciente</h2>
	</header>
	<div class="main-box-body clearfix">
		<div class="row">
			<div class="col-xs-2">Rut:</div>
			<div class="col-xs-4">{{ $record->patient->rut }}</div>
			<div class="col-xs-2">Nombre:</div>
			<div class="col-xs-4">{{ $record->patient->fullname }}</div>
		</div>
		<div class="row">
			<div class="col-xs-2">F. Nacimiento:</div>
			<div class="col-xs-4">{{ $record->patient->birthdate->format('d/m/Y') }}</div>
			<div class="col-xs-2">Edad:</div>
			<div class="col-xs-4">{{ $record->patient->age }} años</div>
		</div>
		<div class="row">
			<div class="col-xs-2">Email:</div>
			<div class="col-xs-4">{{ $record->patient->email }}</div>
			<div class="col-xs-2">Teléfono:</div>
			<div class="col-xs-4">{{ $record->patient->phone }}</div>
		</div>
	</div>
</div>
<div class="main-box">
	<header class="main-box-header clearfix">
		<h2>Datos de la Atención</h2>
	</header>
	<div class="main-box-body clearfix">
		<div class="row">
			<div class="col-xs-2 dvLabel">F. Atención:</div>
			<div class="col-xs-4">{{ $record->attentiondate->format('d/m/Y H:i') }}</div>
			<div class="col-xs-2 dvLabel">Sucursal:</div>
			<div class="col-xs-4">{{ $record->branch->name }}</div>
		</div>
		<div class="row">
			<div class="col-xs-2 dvLabel">Doctor:</div>
			<div class="col-xs-4">{{ ucwords(strtolower($record->doctor->doctor_fullname)) }}</div>
			<div class="col-xs-2 dvLabel">Especialidad:</div>
			<div class="col-xs-4">{{ ucwords(strtolower($record->doctor->doctor_speciality)) }}</div>
		</div>
	</div>
</div>

<div class="main-box">
	<header class="main-box-header clearfix">
		<h2>Ficha Médica</h2>
	</header>
	<div class="main-box-body clearfix">
		<div class="row">
			<div class="col-sm-6">
				{{ Form::label('anamnesis', 'Anamnesis', ['class'=> 'control-label']) }}
				@if($allowEditing)
				{{ Form::textarea('anamnesis', $record->anamnesis, ['class' => 'form-control']) }}
				@else
				<p style="padding: 5px; min-height: 200px; background: #f7f7f7;">
					{!! nl2br($record->anamnesis) !!}
				</p>
				@endif
			</div>
			<div class="col-sm-6">
				{{ Form::label('physical_exam', 'Examenes Físicos', ['class'=> 'control-label']) }}
				@if($allowEditing)
				{{ Form::textarea('physical_exam', $record->physical_exam, ['class' => 'form-control', 'id' => 'physical_exam']) }}
				@else
				<p style="padding: 5px; min-height: 200px; background: #f7f7f7;">
					{!! nl2br($record->physical_exam) !!}
				</p>
				@endif
			</div>
		</div>
		<div class="row">
			<div class="col-sm-6">
				{{ Form::label('diagnosis', 'Diagnóstico', ['class'=> 'control-label']) }}
				@if($allowEditing)
				{{ Form::textarea('diagnosis', $record->diagnosis, ['class' => 'form-control']) }}
				@else
				<p style="padding: 5px; min-height: 200px; background: #f7f7f7;">
					{!! nl2br($record->diagnosis) !!}
				</p>
				@endif
			</div>
			<div class="col-sm-6">
				{{ Form::label('family_history', 'Historial Familiar', ['class'=> 'control-label']) }}
				@if($allowEditing)
				{{ Form::textarea('family_history', $record->patient->family_history, ['class' => 'form-control']) }}
				@else
				<p style="padding: 5px; min-height: 200px; background: #f7f7f7;">
					{!! nl2br($record->family_history) !!}
				</p>
				@endif
			</div>
		</div>
	</div>
</div>

<div class="main-box">
	<header class="main-box-header clearfix">
		<h2>Documentos Adjuntos</h2>
	</header>
	<div class="main-box-body clearfix">
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>Documento</th>
					<th class="text-center">Tamaño</th>
					<th class="text-center">Fecha de Carga</th>
					<th class="text-center">Ver/Descargar</th>
				</tr>
			</thead>
			<tbody>
				@foreach($record->files as $file)
				<tr>
					<td>	
						<a href="{{ route('files.show', [$file->id, $file->filename]) }}" target="_blank">
							<i class="fa fa-file-o"></i>
							{{ $file->realname }}
						</a>
					</td>
					<td class="text-center">{{ number_format($file->size / 1024, 2) }} Mb</td>
					<td class="text-center">{{ $file->created_at->format('d/m/Y H:i') }}</td>
					<td class="text-center">
						<a href="{{ route('files.show', [$file->id, $file->filename]) }}" target="_blank">
							<i class="fa fa-download"></i> Descargar
						</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
</div>

@if($allowEditing)
{{ Form::close() }}
@endif

@if($allowEditing)
<medicalorder v-if="showMedicalOrderDialog"></medicalorder>
@endif

@endsection
@push('scripts')
	<script>
		window.currentDoctor = {
			fullname: '{{ strtoupper($currentDoctor->doctor_fullname) }}',
			speciality: '{{ strtoupper($currentDoctor->doctor_speciality) }}',
			rut: '{{ $currentDoctor->doctor_rut }}',
			rcm: '{{ $currentDoctor->doctor_icm }}'
		};
		window.currentRecord = {
			id: {{ $record->id }}
		};
	</script>
@endpush

resources/views/traumatologist/index.blade.php
@extends('traumatologist.layout')
@section('s-content')

<tradashboard></tradashboard>

@stop

resources/views/traumatologist/print.blade.php
@extends('layouts.print')
@section('content')
<div class="container">
	@include('traumatologist.printcontent')

	<p class="text-center">Fecha de impresión: {{ date('d/m/Y H:i') }}</p>
</div>
<style type="text/css">
	*{
		color: #000 !important;
		font-family: "Lucida Console", "Courier New", monospace;
		font-size: 10px;
		text-transform: uppercase;
	}
	.container{
		margin: auto;
		max-width: 800px;
	}
	.logo{
		display: block;
		margin: 5px;
	}
	.title{
		font-size: 16px;
		font-weight: bold;
		text-transform: uppercase;
	}
	section{
		margin-bottom: 20px;
		padding: 10px;
		border: solid 1px #dee;
	}
	.subtitle{
		font-size: 13px;
		padding: 0;
		margin: 5px 0 10px 0;
		text-transform: uppercase;
		font-weight: bold;
	}
	.dvLabel{
		text-transform: uppercase;
	}
	.contents{
		min-height: 20px;
	}
</style>
<script>
	print();
</script>
@stop

resources/views/traumatologist/printcontent.blade.php
<header style="page-break-before: always;">
	<div class="row">
		<div class="col-xs-12 text-center">
			{{ Html::image('img/logo-print.png', '', ['class' => 'logox']) }}
		</div>
		<div class="col-xs-12 text-center" style="margin-top: 30px;">
			<h1 class="title">Ficha de Atención Médica Nº {{ $record->id }}</h1>
		</div>
	</div>
</header>
<section>
	<h2 class="subtitle">Datos del Paciente</h2>
	<div class="row">
		<div class="col-xs-2 dvLabel">Rut:</div>
		<div class="col-xs-4">{{ $record->patient->rut }}</div>
		<div class="col-xs-2 dvLabel">Nombre:</div>
		<div class="col-xs-4">{{ $record->patient->fullname }}</div>
	</div>
	<div class="row">
		<div class="col-xs-2 dvLabel">F. Nacimiento:</div>
		<div class="col-xs-4">{{ $record->patient->birthdate->format('d/m/Y') }}</div>
		<div class="col-xs-2 dvLabel">Edad:</div>
		<div class="col-xs-4">{{ $record->patient->age }} años</div>
	</div>
	<div class="row">
		<div class="col-xs-2 dvLabel">Email:</div>
		<div class="col-xs-4">{{ $record->patient->email }}</div>
		<div class="col-xs-2 dvLabel">Teléfono:</div>
		<div class="col-xs-4">{{ $record->patient->phone }}</div>
	</div>
</section>
<section>
	<h2 class="subtitle">Datos de la Atención</h2>
	<div class="row">
		<div class="col-xs-2 dvLabel">F. Atención:</div>
		<div class="col-xs-4">{{ $record->attentiondate->format('d/m/Y H:i') }}</div>
		<div class="col-xs-2 dvLabel">Sucursal:</div>
		<div class="col-xs-4">{{ $record->branch->name }}</div>
	</div>
	<div class="row">
		<div class="col-xs-2 dvLabel">Doctor:</div>
		<div class="col-xs-4">{{ ucwords(strtolower($record->doctor->doctor_fullname)) }}</div>
		<div class="col-xs-2 dvLabel">Especialidad:</div>
		<div class="col-xs-4">{{ ucwords(strtolower($record->doctor->doctor_speciality)) }}</div>
	</div>
</section>
<section>
	<h2 class="subtitle">Anamnesis</h2>
	<p class="contents">{!! nl2br($record->anamnesis) !!}</p>
</section>
<section>
	<h2 class="subtitle">Examenes Físicos</h2>
	<p class="contents">{!! nl2br($record->physical_exam) !!}</p>
</section>
<section>
	<h2 class="subtitle">Diagnóstico</h2>
	<p class="contents">{!! nl2br($record->diagnosis) !!}</p>
</section>
<section>
	<h2 class="subtitle">Historial Familiar</h2>
	<p class="contents">{!! nl2br($record->patient->family_history) !!}</p>
</section>

resources/views/traumatologist/records.blade.php
@extends('traumatologist.layout')
@section('s-content')

<div class="main-box">
	<header class="main-box-header clearfix">
		<a href="{{ action('Traumatologist\HomeController@index') }}" class="btn btn-default btn-xs">
			<i class="fa fa-chevron-circle-left"></i> Volver
		</a>
		<div class="pull-right">

		</div>
	</header>
</div>

<div class="main-box">
	<header class="main-box-header clearfix">
		<h2>
			Buscar Fichas Médicas
		</h2>
	</header>
	<div class="main-box-body clearfix">
		{{ Form::open(['method' => 'GET', 'class' => 'form-inline']) }}

		<div class="form-group">
			{{ Form::label('date', 'Fecha de Atención:') }}
			{{ Form::date('date', $selectedDate, ['class' => 'form-control']) }}
		</div>
		<div class="form-group">
			{{ Form::label('patient_rut', 'Rut Paciente:') }}
			{{ Form::text('patient_rut', $selectedPatientRut, ['class' => 'form-control', 'placeholder' => 'ej. 16023817-8']) }}
		</div>
		<div class="form-group">
			{{ Form::label('patient_name', 'Nombre Paciente:') }}
			{{ Form::text('patient_name', $selectedPatientName, ['class' => 'form-control', 'placeholder' => 'ej. Jorge Rojas']) }}
		</div>
		<div class="form-group">
			{{ Form::label('record', 'Nº de Ficha:') }}
			{{ Form::text('record', $selectedRecord, ['class' => 'form-control', 'placeholder' => 'ej. 290']) }}
		</div>

		<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>

		{{ Form::close() }}
	</div>
</div>

@if($records->total() > 0)
<div class="main-box">
	<header class="main-box-header clearfix">
		<h2 class="pull-left">
			Fichas Médicas
			<span class="badge">{{ $records->total() }}</span>
		</h2>

		<div class="text-right">
			<button type="button" id="btnMassivePrint" class="btn btn-default"><i class="fa fa-print"></i> Imprimir</button>
		</div>
	</header>
	<div class="main-box-body clearfix">
		{{ Form::open(['id' => 'frmMassivePrint', 'target' => '_blank', 'action' => 'Traumatologist\RecordController@printMassive']) }}
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th class="text-center">
						<button class="btn btn-default btn-xs" id="btnCheckAll">
							<i class="fa fa-check-square"></i>
						</button>
					</th>
					<th width="120px" class="text-center">Nº de Ficha</th>
					<th width="150px" class="text-center">Fecha Atención</th>
					<th>Paciente</th>
					<th width="120px" class="text-center">Rut</th>
					<th>Sucursal</th>
					<th>Doctor</th>
					<th width="60px">&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				@foreach($records as $record)
				<tr>
					<td class="text-center">
						<label>
							{{ Form::checkbox('print_ids[]', $record->id, false, ['class' => 'print_ids']) }}
						</label>
					</td>
					<td class="text-center">{{ $record->id }}</td>
					<td class="text-center">{{ $record->attentiondate->format('d/m/Y H:i') }}</td>
					<td>{{ $record->patient->fullname }}</td>
					<td class="text-center">{{ $record->patient->rut }}</td>
					<td>{{ $record->branch->name }}</td>
					<td>{{ $record->doctor->name }}</td>
					<td class="text-center">
						<a href="{{ action('Traumatologist\RecordController@edit', $record->id) }}" class="btn btn-default btn-xs">
                            <i class="fa fa-file-text-o"></i>
                        </a>
					</td>
				</tr>
				@endforeach
			</tbody>
			<tfoot>
				<tr>
					<td colspan="8" class="text-right">
						{{ $records->appends(request()->except('page'))->links() }}
					</td>
				</tr>
			</tfoot>
		</table>
		{{ Form::close() }}
	</div>
</div>
@else

@endif
@endsection
@push('scripts')
<script>
$(function(){
	$("#btnCheckAll").click(function(e){
		e.preventDefault();
		if($(".print_ids:checked").length == 0){
			$(".print_ids").prop('checked', true);
		}else{
			$(".print_ids").prop('checked', false);
		}
	});
	$("#btnMassivePrint").click(function(e){
		e.preventDefault();
		if($(".print_ids:checked").length == 0){
			alert("Primero debe selecionar una o mas fichas a imprimir");
			return;
		}else{
			$("#frmMassivePrint").submit();
		}
	});
});
</script>
@endpush